//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuffFilesWpfClient.StuffFilesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StuffFilesServiceReference.IStuffFilesService")]
    public interface IStuffFilesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuffFilesService/GetGreetings", ReplyAction="http://tempuri.org/IStuffFilesService/GetGreetingsResponse")]
        string GetGreetings(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStuffFilesService/GetGreetings", ReplyAction="http://tempuri.org/IStuffFilesService/GetGreetingsResponse")]
        System.Threading.Tasks.Task<string> GetGreetingsAsync(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStuffFilesServiceChannel : StuffFilesWpfClient.StuffFilesServiceReference.IStuffFilesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StuffFilesServiceClient : System.ServiceModel.ClientBase<StuffFilesWpfClient.StuffFilesServiceReference.IStuffFilesService>, StuffFilesWpfClient.StuffFilesServiceReference.IStuffFilesService {
        
        public StuffFilesServiceClient() {
        }
        
        public StuffFilesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StuffFilesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuffFilesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StuffFilesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGreetings(string Name) {
            return base.Channel.GetGreetings(Name);
        }
        
        public System.Threading.Tasks.Task<string> GetGreetingsAsync(string Name) {
            return base.Channel.GetGreetingsAsync(Name);
        }
    }
}
